prompt_pool_path: ./configs/prompts.txt

video:
  width: 1080
  height: 1920
  fps: 24
  duration: 6
  crf: 18
  bitrate: 8M
  audio_bitrate: 192k
  preset: medium
  cover_export: true
  cover_timecode: 0.5

sd:
  backend: diffusers
  model_path: ./models/stable-diffusion
  sampler: ddim
  steps: 30
  guidance_scale: 7.5
  seed:

animate:
  backend: animatediff
  model_path: ./models/animatediff
  motion_module: ./models/animatediff/motion_module
  num_frames: 144
  fps: 24
  strength: 0.65
  seed:

audio:
  enable_bgm: false
  bgm_directory: ./assets/sfx
  normalize: true
  volume: 0.6

prompts:
  extra_texts: []
  extra_styles: []
  extra_tags: []
  blacklist_topics: []
  sensitive_words: []
  max_title_length: 30
  max_desc_length: 120
  max_tags: 5

sampling:
  max_retries: 10
  stats_log: true
  fallback:
    enabled: true
    title: "今天也要加油"
    description: "保持创作与节奏，见证每天的小进步。"
    tags: ["日常", "励志", "记录"]
    prompt_text: "清新剪贴风, 竖屏, 简约背景, 主角置中"
  blacklist: []
  safe_words: ["温暖", "可爱", "元气"]

scheduler:
  batch_size: 1
  concurrency: 2
  min_free_vram_mb: 3000
  hard_serial: true
  max_retries: 2
  cooldown_sec: 3
  index_file: outputs/index.jsonl
  log_dir: outputs/logs
  lock_path: locks/gpu.lock

storage:
  output_dir: outputs
  cover_dir: outputs/covers
  frames_dir: outputs/frames
  tmp_dir: outputs/tmp

uploader:
  provider: "none"
  target: douyin
  visibility: private
  cookie_path: ./configs/cookies.json
  extra:
    api_base: https://open.douyin.com
    platformVersion: "12"
    appPackage: com.ss.android.ugc.aweme
    appActivity: com.ss.android.ugc.aweme.main.MainActivity

safety:
  enable_sensitive_scan: true
  enable_ad_scan: true
  retry_on_violation: false

runtime:
  seed:
  dry_run: false

postprocess:
  subtitle: false
  watermark: false

retry:
  max_attempts: 3
  backoff_factor: 2
  jitter_ms: 150
  ffmpeg:
    enabled: true
    retryable_exit_codes: [1, 255]

logging:
  jsonl_path: "outputs/logs/pipeline.jsonl"

profiles:
  dir: "profiles"
